# Generated by Django 6.1.1 on 2026-09-18 18:06

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('mode_of_booking', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=20)),
                ('booked_by', models.CharField(blank=True, help_text='Required if offline', max_length=200, null=True)),
                ('check_in_date', models.DateField(default=django.utils.timezone.now)),
                ('check_out_date', models.DateField(blank=True, null=True)),
                ('is_checked_out', models.BooleanField(default=False)),
                ('room_rate_per_day', models.DecimalField(decimal_places=2, default=Decimal('1000.00'), max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='FoodCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resort.guest')),
            ],
        ),
    ]
