# Generated by Django 6.1.1 on 2026-09-18 18:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodcharge',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='foodcharge',
            name='description',
        ),
        migrations.AddField(
            model_name='foodcharge',
            name='item_name',
            field=models.CharField(default='Food Item', max_length=255),
        ),
        migrations.AddField(
            model_name='foodcharge',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='foodcharge',
            name='rate_per_unit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='guest',
            name='extra_bed_needed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest',
            name='extra_bed_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='guest',
            name='number_of_adults',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='guest',
            name='number_of_children',
            field=models.IntegerField(default=0),
        ),
    ]
