# Generated by Django 6.1.1 on 2026-09-18 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0002_remove_foodcharge_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='room_rate_per_day',
        ),
        migrations.CreateModel(
            name='BookedRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=100)),
                ('room_number', models.CharField(max_length=50)),
                ('rate_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resort.guest')),
            ],
        ),
    ]
