# Generated by Django 6.0.1 on 2026-09-22 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel_manager', '0001_initial'),
        ('resort', '0003_remove_guest_room_rate_per_day_bookedroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedroom',
            name='physical_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='channel_manager.physicalroom'),
        ),
        migrations.AddField(
            model_name='bookedroom',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booked_rooms', to='channel_manager.reservation'),
        ),
        migrations.AlterField(
            model_name='bookedroom',
            name='guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resort.guest'),
        ),
    ]
