# Generated by Django 6.0.1 on 2026-09-24 14:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0004_bookedroom_physical_room_bookedroom_reservation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(max_length=255)),
                ('shop_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bill_number', models.CharField(blank=True, max_length=100, null=True)),
                ('bill_photo', models.FileField(blank=True, null=True, upload_to='expense_bills/')),
            ],
        ),
    ]
