# Generated by Django 6.1.1 on 2026-09-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0005_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Online', 'Online')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
